<a href="https://colab.research.google.com/github/241b266-Sudhanshu/APS-LAB/blob/main/Lab_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Warshall algorithm to find reachability between all pairs of vertices in a graph.
Problem Description:
Understand transitive closure of a graph. Use Python to compute reachability using matrix method.

#Theory
Warshall algorithm finds whether a path exists between every pair of vertices. It updates the adjacency matrix step by step. If there is a path from i to j through k, then the entry becomes 1.

## Algorithm
1. Represent graph using adjacency matrix.
2. For each intermediate vertex k
3. Check all pairs i and j
4. Update value if path exists through k
4. Repeat for all vertices


In [ ]:
def warshall(graph):

    n = len(graph)

    for k in range(n):
        for i in range(n):
            for j in range(n):
                graph[i][j] = graph[i][j] or (graph[i][k] and graph[k][j])

    return graph


In [ ]:
graph = [
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1],
[0, 0, 0, 0]
]

result = warshall(graph)

print("Transitive Closure Matrix:")

for row in result:
    print(row)

Transitive Closure Matrix:
[0, 1, 1, 1]
[0, 0, 1, 1]
[0, 0, 0, 1]
[0, 0, 0, 0]


Now, let's implement
1. Modify program to take matrix input from user
2. Apply algorithm on graph with 5 vertices
3. Compare Warshall with Floyd algorithm
4. Display path existence in readable format

In [2]:


import numpy as np


n = 5
print("Enter adjacency matrix (5x5):")
graph = []
for i in range(n):
    row = list(map(int, input().split()))
    graph.append(row)

graph = np.array(graph)


def warshall(matrix):
    n = len(matrix)
    reach = matrix.copy()
    for k in range(n):
        for i in range(n):
            for j in range(n):
                reach[i][j] = reach[i][j] or (reach[i][k] and reach[k][j])
    return reach


def floyd(matrix):
    n = len(matrix)
    dist = [[float('inf')] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if matrix[i][j] != 0:
                dist[i][j] = matrix[i][j]
        dist[i][i] = 0

    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]
    return dist


warshall_result = warshall(graph)
floyd_result = floyd(graph)


print("\nWarshall (Path Existence Matrix):")
for row in warshall_result:
    print(row)

print("\nReadable Path Existence:")
for i in range(n):
    for j in range(n):
        if i != j:
            if warshall_result[i][j]:
                print(f"Path exists from {i+1} to {j+1}")
            else:
                print(f"No path from {i+1} to {j+1}")

print("\nFloyd (Shortest Path Matrix):")
for row in floyd_result:
    print(row)


Enter adjacency matrix (5x5):
1 5 9 8 5
7 23 8 45 96
7 4 1 8 5
 74 88 93 14 25
1  2  3   4  5

Warshall (Path Existence Matrix):
[1 5 9 8 5]
[ 7 23  8 45 96]
[7 4 1 8 5]
[74 88 93 14 25]
[1 2 3 4 5]

Readable Path Existence:
Path exists from 1 to 2
Path exists from 1 to 3
Path exists from 1 to 4
Path exists from 1 to 5
Path exists from 2 to 1
Path exists from 2 to 3
Path exists from 2 to 4
Path exists from 2 to 5
Path exists from 3 to 1
Path exists from 3 to 2
Path exists from 3 to 4
Path exists from 3 to 5
Path exists from 4 to 1
Path exists from 4 to 2
Path exists from 4 to 3
Path exists from 4 to 5
Path exists from 5 to 1
Path exists from 5 to 2
Path exists from 5 to 3
Path exists from 5 to 4

Floyd (Shortest Path Matrix):
[0, np.int64(5), np.int64(8), np.int64(8), np.int64(5)]
[np.int64(7), 0, np.int64(8), np.int64(15), np.int64(12)]
[np.int64(6), np.int64(4), 0, np.int64(8), np.int64(5)]
[np.int64(26), np.int64(27), np.int64(28), 0, np.int64(25)]
[np.int64(1), np.int64(2), np.int6

## Find shortest paths between all pairs of vertices using Floyd Warshall algorithm.

#Understand all pairs shortest path problem. Implement dynamic programming approach in Python.

* Given a weighted graph with positive or negative edge weights, find
shortest distances between every pair of vertices.

# Theory
Floyd Warshall algorithm computes shortest paths between all pairs of nodes. It updates the distance matrix by checking if a shorter path exists through an intermediate vertex. Works with negative weights but fails with negative cycles.

Algorithm
1. Represent graph using distance matrix.
2. Initialize matrix with given weights.
3. Set distance of node to itself as 0.
4. For each intermediate vertex k
5. Update distance[i][j] = min(distance[i][j], distance[i][k] + distance[k][j])
6. Repeat for all vertices

In [4]:
def floyd_warshall(graph):

    n = len(graph)

    dist = []
    for i in range(n):
        dist.append(graph[i][:])

    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]

    return dist



In [5]:
INF = float('inf')

def floyd_warshall(graph):

    n = len(graph)

    dist = []
    for i in range(n):
        dist.append(graph[i][:])

    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]

    return dist

graph = [
[0, 3, INF, 7],
[8, 0, 2, INF],
[5, INF, 0, 1],
[2, INF, INF, 0]
]

result = floyd_warshall(graph)

print("Shortest distance matrix:")

for row in result:
    print(row)

Shortest distance matrix:
[0, 3, 5, 6]
[5, 0, 2, 3]
[3, 6, 0, 1]
[2, 5, 7, 0]


# Excercise
1. Take matrix input from user
2. Detect negative cycle in graph
3. Print shortest path between two given vertices
4. Compare with Dijkstra algorithm

In [7]:
import numpy as np

n = int(input("Enter number of vertices (e.g., 5): "))
print(f"Enter adjacency matrix ({n}x{n}), use 0 if no edge:")
graph = []
for i in range(n):
    row = list(map(int, input().split()))
    graph.append(row)

graph = np.array(graph)

def floyd_warshall(matrix):
    n = len(matrix)
    dist = [[float('inf')] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if matrix[i][j] != 0:
                dist[i][j] = matrix[i][j]
        dist[i][i] = 0


    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]


    negative_cycle = False
    for i in range(n):
        if dist[i][i] < 0:
            negative_cycle = True
            break

    return dist, negative_cycle


import heapq

def dijkstra(matrix, src):
    n = len(matrix)
    dist = [float('inf')] * n
    dist[src] = 0
    pq = [(0, src)]

    while pq:
        d, u = heapq.heappop(pq)
        if d > dist[u]:
            continue
        for v in range(n):
            if matrix[u][v] != 0:
                if dist[u] + matrix[u][v] < dist[v]:
                    dist[v] = dist[u] + matrix[u][v]
                    heapq.heappush(pq, (dist[v], v))
    return dist


floyd_result, has_negative_cycle = floyd_warshall(graph)

print("\nFloyd-Warshall Result (Shortest Path Matrix):")
for row in floyd_result:
    print(row)

if has_negative_cycle:
    print("\nGraph contains a NEGATIVE cycle!")
else:
    print("\nNo negative cycle detected.")


while True:
    try:
        src = int(input(f"\nEnter source vertex (1-based index, 1-{n}): ")) - 1
        if 0 <= src < n:
            break
        else:
            print(f"Invalid source vertex. Please enter a number between 1 and {n}.")
    except ValueError:
        print("Invalid input. Please enter a number.")

while True:
    try:
        dest = int(input(f"Enter destination vertex (1-based index, 1-{n}): ")) - 1
        if 0 <= dest < n:
            break
        else:
            print(f"Invalid destination vertex. Please enter a number between 1 and {n}.")
    except ValueError:
        print("Invalid input. Please enter a number.")


if floyd_result[src][dest] == float('inf'):
    print(f"No path exists from {src+1} to {dest+1}")
else:
    print(f"Shortest path from {src+1} to {dest+1} (Floyd-Warshall): {floyd_result[src][dest]}")

dijkstra_result = dijkstra(graph, src)
if dijkstra_result[dest] == float('inf'):
    print(f"No path exists from {src+1} to {dest+1} (Dijkstra)")
else:
    print(f"Shortest path from {src+1} to {dest+1} (Dijkstra): {dijkstra_result[dest]}")

Enter number of vertices (e.g., 5): 3
Enter adjacency matrix (3x3), use 0 if no edge:
1 45 96
41 26 29
1 11 12

Floyd-Warshall Result (Shortest Path Matrix):
[0, np.int64(45), np.int64(74)]
[np.int64(30), 0, np.int64(29)]
[np.int64(1), np.int64(11), 0]

No negative cycle detected.

Enter source vertex (1-based index, 1-3): 2
Enter destination vertex (1-based index, 1-3): 3
Shortest path from 2 to 3 (Floyd-Warshall): 29
Shortest path from 2 to 3 (Dijkstra): 29
